version: "3.2"
services:

  apache:

    image: thalesmee
    depends_on:
      - mariadb
    ports:
      - "80:80"
    environment:
       - DATABASE=mariadb
       - PHP.mysqli.default_port=3306

  mariadb:
    image: mariadb:10.5.9
    restart : always
    ports: 
      - 3306:3306
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pipo2000
      - MYSQL_DATABASE=bdmee_prod

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:

  db-volume:
