version: "3.2"
services:

  apache:

    build: './'
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html/
      - ./php.ini:/etc/php5/cli/php.ini
      - ./php.ini:/etc/php5/apache/php.ini
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf

  db:

    image: mariadb:latest
    restart : always
    ports: 
      - 3306:3306
    command: --lower_case_table_names=1
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pipo2000
      - MYSQL_DATABASE=bdmee_prod

  phpmyadmin:

    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 30000000

volumes:

  db-volume:
