version: "3.2"
services:

  apache:
    image: thalesmee:latest
    container_name: thalesmee-apache
    ports:
       - 80:80
    environment:
       - DATABASE=db
       - PHP.mysqli.default_port=3305

  db:

    image: mysql:5.7
    restart : always
    ports: 
      - 3305:3306
    command: --lower_case_table_names=1
    # volumes:
    #   - db-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pipo2000
      - MYSQL_DATABASE=bdmee_prod
      - MYSQL_USER=mee
      - MYSQL_PASSWORD=pipo

  # phpmyadmin:
  #   depends_on:
  #     - db
  #   image: docker-ccsl-virtual.repo.aes.alcatel.fr:8443/phpmyadmin:5.0-apache
  #   restart: always
  #   ports:
  #     - "8081:80"
  #   environment:
  #     PMA_HOST: db
  #     UPLOAD_LIMIT: 30000000
